name: Lint
on:
  push:
  workflow_dispatch: # debug

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm redocly lint openapi/openapi.yaml --format github-actions
